module.exports = [
  {
    boat_id: 1,
    codename: "SECRETLOVE",
    name: "SECRET LOVE",
    portrait: "img_1_1.jpg",
    video1: "http://www.youtube.com/v/W6V6LYyhrpk&hl=en_US&fs=1&rel=0",
    video2: "http://www.youtube.com/v/2M4_n_110qU&hl=en&fs=1",
    pageviews: 13120,
    images: [
      {
        image_id: 1,
        boat_id: 1,
        path: "img_1_1.jpg",
      },
      {
        image_id: 102,
        boat_id: 1,
        path: "img_1_102.jpg",
      },
      {
        image_id: 101,
        boat_id: 1,
        path: "img_1_101.jpg",
      },
      {
        image_id: 104,
        boat_id: 1,
        path: "img_1_104.jpg",
      },
      {
        image_id: 106,
        boat_id: 1,
        path: "img_1_106.jpg",
      },
      {
        image_id: 107,
        boat_id: 1,
        path: "img_1_107.jpg",
      },
      {
        image_id: 108,
        boat_id: 1,
        path: "img_1_108.jpg",
      },
      {
        image_id: 109,
        boat_id: 1,
        path: "img_1_109.jpg",
      },
      {
        image_id: 111,
        boat_id: 1,
        path: "img_1_111.jpg",
      },
      {
        image_id: 113,
        boat_id: 1,
        path: "img_1_113.jpg",
      },
      {
        image_id: 115,
        boat_id: 1,
        path: "img_1_115.jpg",
      },
      {
        image_id: 116,
        boat_id: 1,
        path: "img_1_116.jpg",
      },
      {
        image_id: 117,
        boat_id: 1,
        path: "img_1_117.jpg",
      },
      {
        image_id: 121,
        boat_id: 1,
        path: "img_1_121.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 1,
        category: "Specifications",
        attributes: [
          "Smoking permitted (outside only)",
          "Games (X-Box, board games, etc.)",
          "Movie library (300 + DVD's)",
          "Entertainment / Theater System",
          "Fishing equipment",
          "Scuba Diving permitted. Must be certified",
          "Snorkle, mask, and fins for (4)",
          "Ski-Bob",
          "15' Navarone w/ 90 hp o/b",
          "(2) person Ocean Kayak",
          "Water toys:",
          "Spa services available",
          "Jacuzzi hot tub",
          "Air conditioning throughout",
          "Number of day heads (1)",
          "Number of heads (6)",
          "(4) guest cabins plus crew",
          "Crew: Captain plus 1 (max crew 3 total)",
          "US Coast Guard certified for up to 65 guests",
          "Date of last refit: 2007",
          "Date of launch: 1979",
          "Range: 300 nautical miles",
          "Fuel consumption: 65 gph",
          "Cruising speed: 12 - 14 knots",
          "Height: 36'",
          "Draft: 6' 1\"",
          "Beam: 19'6\"",
          "Length: 80'",
        ],
      },
    ],
    oldVideo1:
      '<object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/W6V6LYyhrpk&hl=en_US&fs=1&rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/W6V6LYyhrpk&hl=en_US&fs=1&rel=0" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>',
    oldVideo2:
      '<object width="425" height="344"><param name="movie"\r\nvalue="http://www.youtube.com/v/2M4_n_110qU&hl=en&fs=1"></param><param\r\nname="allowFullScreen" value="true></param><param name="allowscriptaccess"\r\nvalue="always"></param><embed\r\nsrc="http://www.youtube.com/v/2M4_n_110qU&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425"\r\nheight="344"></embed></object>',
  },
  {
    boat_id: 2,
    codename: "TYRONE",
    name: "TYRONE",
    portrait: "img_2_346.jpg",
    video1: "",
    video2: "",
    pageviews: 4693,
    images: [
      {
        image_id: 346,
        boat_id: 2,
        path: "img_2_346.jpg",
      },
      {
        image_id: 345,
        boat_id: 2,
        path: "img_2_345.jpg",
      },
      {
        image_id: 342,
        boat_id: 2,
        path: "img_2_342.jpg",
      },
      {
        image_id: 343,
        boat_id: 2,
        path: "img_2_343.jpg",
      },
      {
        image_id: 344,
        boat_id: 2,
        path: "img_2_344.jpg",
      },
      {
        image_id: 394,
        boat_id: 2,
        path: "img_2_394.jpg",
      },
      {
        image_id: 395,
        boat_id: 2,
        path: "img_2_395.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 2,
        category: "Specifications",
        attributes: [
          "Inflatable tender w/ 5hp motor",
          "(1) Person kayak",
          "BBQ grill",
          "Am/Fm CD stereo",
          "Single side band radio",
          "VHF radio",
          "Furuno Radar",
          "Trimble GPS",
          "EPIRB",
          "1805 Sq. ft of sail",
          "8' 6\" Draft",
          "15' Beam",
          "60' On deck",
          "75' LOA",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 3,
    codename: "SCARAB",
    name: "SCARAB",
    portrait: "img_3_52.jpg",
    video1: "http://www.youtube.com/embed/wUmDDZpuVvo?rel=0",
    video2: "http://www.youtube.com/embed/MCtVGbqYyZw?rel=0",
    pageviews: 3951,
    images: [
      {
        image_id: 82,
        boat_id: 3,
        path: "img_3_82.jpg",
      },
      {
        image_id: 83,
        boat_id: 3,
        path: "img_3_83.jpg",
      },
      {
        image_id: 84,
        boat_id: 3,
        path: "img_3_84.jpg",
      },
      {
        image_id: 638,
        boat_id: 3,
        path: "img_3_638.jpg",
      },
      {
        image_id: 640,
        boat_id: 3,
        path: "img_3_640.jpg",
      },
      {
        image_id: 639,
        boat_id: 3,
        path: "img_3_639.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 3,
        category: "Specifications",
        attributes: [
          "(2) Large coolers for provisions",
          "(2) Ocean Kayaks (for expedition charters)",
          "Light fishing gear",
          "Pipewelders buggie top",
          "Stereo with CD / MP3",
          "GPS/VHF/Depthsounder",
          "Electronics:",
          "Head in cuddy cabin",
          "V-Berth for two",
          "Accomodates up to 6 guests for day charters",
          "Model: SCARAB",
          "Builder: Wellcraft",
          "Fuel Capacity: 150 gallons",
          "2 x 200 HP engines",
          "8' Beam",
          "30' LOA",
        ],
      },
      {
        boat_id: 3,
        category: "Description",
        attributes: [
          "If you are into adventure, we can bring Ocean Kayaks and provisions and do an expedition charter off the beaten path for an unforgettable eco experience.",
          "With exhilarating cruising speed, the SCARAB can cover more ground more quickly so you get to see more sights and get to spend more time doing what you want to do. Whether you want to go to a secluded beach for some swimming, and then stay for a picnic, or do a little fishing on the way to one of the islands for lunch and shopping, the SCARAB will get you there in style.",
        ],
      },
    ],
    oldVideo1:
      '<iframe title="YouTube video player" width="480" height="390" src="http://www.youtube.com/embed/wUmDDZpuVvo?rel=0" frameborder="0" allowfullscreen></iframe>',
    oldVideo2:
      '<iframe title="YouTube video player" width="480" height="390" src="http://www.youtube.com/embed/MCtVGbqYyZw?rel=0" frameborder="0" allowfullscreen></iframe>',
  },
  {
    boat_id: 4,
    codename: "RandR",
    name: "RandR",
    portrait: "img_4_53.jpg",
    video1: "http://www.youtube.com/v/diP6XEEzhic&hl=en&fs=1&rel=0",
    video2: "",
    pageviews: 734,
    images: [
      {
        image_id: 53,
        boat_id: 4,
        path: "img_4_53.jpg",
      },
      {
        image_id: 54,
        boat_id: 4,
        path: "img_4_54.jpg",
      },
      {
        image_id: 55,
        boat_id: 4,
        path: "img_4_55.jpg",
      },
      {
        image_id: 56,
        boat_id: 4,
        path: "img_4_56.jpg",
      },
      {
        image_id: 57,
        boat_id: 4,
        path: "img_4_57.jpg",
      },
      {
        image_id: 58,
        boat_id: 4,
        path: "img_4_58.jpg",
      },
      {
        image_id: 59,
        boat_id: 4,
        path: "img_4_59.jpg",
      },
      {
        image_id: 60,
        boat_id: 4,
        path: "img_4_60.jpg",
      },
      {
        image_id: 61,
        boat_id: 4,
        path: "img_4_61.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 4,
        category: "Specifications",
        attributes: [
          "Crew: Captain plus 1 (max. crew 3 total)",
          "US Coast Guard certified for up to 49 guests",
          "Tender: 16' Zodiac inflateable",
          "Date of launch: 2000",
          "Range: 250 nautical miles",
          "Fuel consumption: 30 gallons per hour",
          "Cruising speed: 18 knots",
          "Height: 25'",
          "Draft: 4' 6\"",
          "Beam: 19' 6\"",
          "Length: 50'",
        ],
      },
      {
        boat_id: 4,
        category: "Description",
        attributes: [
          "For booking information and availability, please contact your charter broker.",
          "",
        ],
      },
    ],
    oldVideo1:
      '<object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/diP6XEEzhic&hl=en&fs=1&rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/diP6XEEzhic&hl=en&fs=1&rel=0" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>',
    oldVideo2: "",
  },
  {
    boat_id: 6,
    codename: "SeaRay46",
    name: "LIBERTY46",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 7961,
    images: [
      {
        image_id: 65,
        boat_id: 6,
        path: "img_6_65.jpg",
      },
      {
        image_id: 66,
        boat_id: 6,
        path: "img_6_66.jpg",
      },
      {
        image_id: 67,
        boat_id: 6,
        path: "img_6_67.jpg",
      },
      {
        image_id: 68,
        boat_id: 6,
        path: "img_6_68.jpg",
      },
      {
        image_id: 69,
        boat_id: 6,
        path: "img_6_69.jpg",
      },
      {
        image_id: 70,
        boat_id: 6,
        path: "img_6_70.jpg",
      },
      {
        image_id: 71,
        boat_id: 6,
        path: "img_6_71.jpg",
      },
      {
        image_id: 72,
        boat_id: 6,
        path: "img_6_72.jpg",
      },
      {
        image_id: 73,
        boat_id: 6,
        path: "img_6_73.jpg",
      },
      {
        image_id: 74,
        boat_id: 6,
        path: "img_6_74.jpg",
      },
      {
        image_id: 76,
        boat_id: 6,
        path: "img_6_76.jpg",
      },
      {
        image_id: 77,
        boat_id: 6,
        path: "img_6_77.jpg",
      },
      {
        image_id: 80,
        boat_id: 6,
        path: "img_6_80.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 6,
        category: "Specifications",
        attributes: [
          "11kw Westerbeke Generator",
          "Twin 6v92TA Detroit Diesels",
          "4' Draft",
          "15' Beam",
          "46' LOA",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 7,
    codename: "FULLCIRCLE",
    name: "FULL CIRCLE",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 19,
    images: [
      {
        image_id: 86,
        boat_id: 7,
        path: "img_7_86.jpg",
      },
      {
        image_id: 87,
        boat_id: 7,
        path: "img_7_87.jpg",
      },
      {
        image_id: 88,
        boat_id: 7,
        path: "img_7_88.jpg",
      },
      {
        image_id: 89,
        boat_id: 7,
        path: "img_7_89.jpg",
      },
      {
        image_id: 90,
        boat_id: 7,
        path: "img_7_90.jpg",
      },
      {
        image_id: 91,
        boat_id: 7,
        path: "img_7_91.jpg",
      },
      {
        image_id: 92,
        boat_id: 7,
        path: "img_7_92.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 7,
        category: "Specifications",
        attributes: ["LOA: 29'"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 8,
    codename: "KNOTTYKAT",
    name: "KNOTTY KAT",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 7928,
    images: [
      {
        image_id: 93,
        boat_id: 8,
        path: "img_8_93.jpg",
      },
      {
        image_id: 94,
        boat_id: 8,
        path: "img_8_94.jpg",
      },
      {
        image_id: 95,
        boat_id: 8,
        path: "img_8_95.jpg",
      },
      {
        image_id: 96,
        boat_id: 8,
        path: "img_8_96.jpg",
      },
      {
        image_id: 97,
        boat_id: 8,
        path: "img_8_97.jpg",
      },
      {
        image_id: 98,
        boat_id: 8,
        path: "img_8_98.jpg",
      },
      {
        image_id: 165,
        boat_id: 8,
        path: "img_8_165.jpg",
      },
      {
        image_id: 166,
        boat_id: 8,
        path: "img_8_166.jpg",
      },
      {
        image_id: 167,
        boat_id: 8,
        path: "img_8_167.jpg",
      },
      {
        image_id: 168,
        boat_id: 8,
        path: "img_8_168.jpg",
      },
      {
        image_id: 169,
        boat_id: 8,
        path: "img_8_169.jpg",
      },
      {
        image_id: 185,
        boat_id: 8,
        path: "img_8_185.jpg",
      },
      {
        image_id: 186,
        boat_id: 8,
        path: "img_8_186.jpg",
      },
      {
        image_id: 187,
        boat_id: 8,
        path: "img_8_187.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 8,
        category: "Specifications",
        attributes: [
          "Crew : 2",
          "Max. number of guests : 12",
          "Year of launch : 1995",
          "Max. speed : 10 knots",
          "Range @ cruise : 480 nm",
          "Fuel consuption : 1.5 GPH @ cruise",
          "Cruising speed : 8 knots",
          "Height : 52'",
          'Draft : 36"',
          "Beam : 15'",
          "Length : 35'",
        ],
      },
      {
        boat_id: 8,
        category: "Crew Profile",
        attributes: [
          'Captain Rick Butler was born on Cape Cod in 1959. He started boating at an early age sailing around Cape Cod with his family. The summer of his senior year in High School, he assisted teaching sailing for the Dennis / Yarmouth High School Sailing Program. Captain Rick has participated in several FIGOWI regattas, and one Classic Wooden Sailboat race which included two boats owned and operated by the Kennedy family. In 1992, Rick obtained his USCG Masters License. Since then, he has been operating boats and yachts from New England to Florida, and has delivered several up and down the East coast. His love and respect for the sea has been a life long experience and commitment.\r\n\r\nFirst mate Kathleen Butler was born in 1959. She graduated from Avon High School in 1977, and moved to Cape Cod in 1986. She attended Fisher College and received an associates degree in Paralegal Studies. After years of working in the legal field, she currently works as an Administrative Assistant when she isn\'t crewing on "KNOTTY KAT". She also has worked in the hospitality business for over 20 years, and loves working with the public. Living on Cape Cod and spending a few winters in Florida has given her the opportunity to experience cruising in Nantucket Sound and the Gulf of Mexico. Captain Rick and Kathleen have been together for 6 years and married in January of 2008 on Fort Lauderdale Beach. After the reception, held at the Cabana Tiki Bar, they went on a 7 - day Caribbean Cruise. They now live in Yarmouth, Massachusetts. Their goal is to operate "KNOTTY KAT" on Cape Cod in the summer and Florida in the winter.',
        ],
      },
      {
        boat_id: 8,
        category: "Vessel Description",
        attributes: [
          'Island Packet catamarans are considered to be "unsinkable" due to their immense reserve bouyancy in the unique forward Delta Pod centered between the primary hulls. Safety equipment consists of (14) adult and (6) child Type I life jackets, inflateable tender, EPIRB, and First Aid Kit. Unlike most catamarans, "KNOTTY KAT" has a beam of 15\', which allows access to most standard size slips. Also unlike most catamarans, the forward deck is solid fiberglass, not a trampoline net, which creates more room and has a sun bathing cushion that can accomodate (4) adults. The cockpit area comfortably seats (6) adults, and has a retractable Bimini top allowing the choice of sun, or shade.',
        ],
      },
      {
        boat_id: 8,
        category: "Accommodations",
        attributes: [
          "2 Identical cabins with 6'4\" head room and queen sized berths, cedar lined cupboards and hanging locker storage, ensuite heads with showers / mini tubs. AC and heat throughout. Entertainment system includes TV, DVD player, Jensen stereo.",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 9,
    codename: "DRESSBLUE",
    name: "DRESS BLUE",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 256,
    images: [
      {
        image_id: 125,
        boat_id: 9,
        path: "img_9_125.jpg",
      },
      {
        image_id: 127,
        boat_id: 9,
        path: "img_9_127.jpg",
      },
      {
        image_id: 128,
        boat_id: 9,
        path: "img_9_128.jpg",
      },
      {
        image_id: 129,
        boat_id: 9,
        path: "img_9_129.jpg",
      },
      {
        image_id: 130,
        boat_id: 9,
        path: "img_9_130.jpg",
      },
      {
        image_id: 131,
        boat_id: 9,
        path: "img_9_131.jpg",
      },
      {
        image_id: 132,
        boat_id: 9,
        path: "img_9_132.jpg",
      },
      {
        image_id: 133,
        boat_id: 9,
        path: "img_9_133.jpg",
      },
      {
        image_id: 134,
        boat_id: 9,
        path: "img_9_134.jpg",
      },
      {
        image_id: 135,
        boat_id: 9,
        path: "img_9_135.jpg",
      },
      {
        image_id: 136,
        boat_id: 9,
        path: "img_9_136.jpg",
      },
      {
        image_id: 137,
        boat_id: 9,
        path: "img_9_137.jpg",
      },
      {
        image_id: 161,
        boat_id: 9,
        path: "img_9_161.jpg",
      },
      {
        image_id: 162,
        boat_id: 9,
        path: "img_9_162.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 9,
        category: "Features",
        attributes: [
          "A/C Throughout Cabin",
          "Smoking permitted on deck only.",
          "Stereo, AM/FM, CD",
          "Flat screen TV",
          "Fishing equipment included. Blues, Bass, Tuna.",
          "SCUBA Diving Permitted w/ PADI or NAUI card and own gear.",
          "8' 6\"  Walker Bay Inflatable Tender / 4 hp Yamaha 4 stroke outboard",
        ],
      },
      {
        boat_id: 9,
        category: "Description",
        attributes: [
          "Galley ",
          "Dinette /",
          "Enclosed Head / ",
          "V-Berth /  ",
          "Max Number of Guests: 6 /    Crew: 2 /  ",
          "2004 Wellcraft Sportfish - Express /  ",
        ],
      },
      {
        boat_id: 9,
        category: "Specifications",
        attributes: [
          "Generator: Koeler 5kw",
          "Twin Volvo TAMD Turbo Diesels 370 hp",
          "Max Speed: 30 knots",
          "Range @ Cruise: 400 knot miles\r\n",
          "Fuel Consumption @ Cruise: 25 GPH",
          "Cruising Speed: 24 knots",
          "Height: 10'",
          "Draft: 3'",
          "Beam: 12' 6\"",
          "LOA: 38' 9\"",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 11,
    codename: "BAYSPIRIT",
    name: "BAY SPIRIT",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 6712,
    images: [
      {
        image_id: 150,
        boat_id: 11,
        path: "img_11_150.jpg",
      },
      {
        image_id: 151,
        boat_id: 11,
        path: "img_11_151.jpg",
      },
      {
        image_id: 152,
        boat_id: 11,
        path: "img_11_152.jpg",
      },
      {
        image_id: 155,
        boat_id: 11,
        path: "img_11_155.jpg",
      },
      {
        image_id: 299,
        boat_id: 11,
        path: "img_11_299.jpg",
      },
      {
        image_id: 454,
        boat_id: 11,
        path: "img_11_454.jpg",
      },
      {
        image_id: 452,
        boat_id: 11,
        path: "img_11_452.jpg",
      },
      {
        image_id: 453,
        boat_id: 11,
        path: "img_11_453.jpg",
      },
      {
        image_id: 641,
        boat_id: 11,
        path: "img_11_641.jpg",
      },
      {
        image_id: 642,
        boat_id: 11,
        path: "img_11_642.jpg",
      },
      {
        image_id: 643,
        boat_id: 11,
        path: "img_11_643.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 11,
        category: "Accommodations",
        attributes: ["Day Heads: 2", "Large Heated / Air Conditioned cabin"],
      },
      {
        boat_id: 11,
        category: "Specifications",
        attributes: [
          "Crew: 3",
          "USCG Certified for up to 49 guests",
          "Date of Launch: 2001",
          "Builder: Ron Cooper Yachts",
          "Max Speed: 22 Knots",
          "Range @ Cruising Speed: 400 ktm",
          "Fuel Consumption @ Cruise: 20 GPH",
          "Cruising Speed: 17 Knots",
          "3' 6\" Draft",
          "24' Beam",
          "63' 3\"  LOA",
        ],
      },
      {
        boat_id: 11,
        category: "Description",
        attributes: ["Smoking Allowed onboard (on deck only)"],
      },
      {
        boat_id: 11,
        category: "Features",
        attributes: [
          "DVD / CD / XM Sat-Radio",
          "Entertainment System: (2) Large TVs in Salon",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 13,
    codename: "GULFSTREAMCONTRACTING",
    name: "GULF STREAM CONTRACTING",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 15,
    images: [
      {
        image_id: 170,
        boat_id: 13,
        path: "img_13_170.jpg",
      },
      {
        image_id: 176,
        boat_id: 13,
        path: "img_13_176.jpg",
      },
      {
        image_id: 177,
        boat_id: 13,
        path: "img_13_177.jpg",
      },
      {
        image_id: 178,
        boat_id: 13,
        path: "img_13_178.jpg",
      },
      {
        image_id: 179,
        boat_id: 13,
        path: "img_13_179.jpg",
      },
      {
        image_id: 180,
        boat_id: 13,
        path: "img_13_180.jpg",
      },
      {
        image_id: 181,
        boat_id: 13,
        path: "img_13_181.jpg",
      },
      {
        image_id: 182,
        boat_id: 13,
        path: "img_13_182.jpg",
      },
      {
        image_id: 183,
        boat_id: 13,
        path: "img_13_183.jpg",
      },
      {
        image_id: 184,
        boat_id: 13,
        path: "img_13_184.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 13,
        category: "Description",
        attributes: [
          "This series of photos shows the aft deck repair on a 46' Sea Ray express cruiser. All the wet balsa coring was removed, fresh glass laid down, all new balsa core mat was installed on a layer of bedding compound, and a series of layers of fiberglass cloth was used to build up the deck. Hatch openings were masked and new gel coat and non-skid were applied. ",
          "Marine Restoration:\r\n\r\nFishing Guide Services:\r\n\r\nContact:\r\nMark Spetalunas\r\n774-994-1867.                                                                                                                            .",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 14,
    codename: "DEFIANT",
    name: "DEFIANT",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 20,
    images: [
      {
        image_id: 171,
        boat_id: 14,
        path: "img_14_171.jpg",
      },
      {
        image_id: 172,
        boat_id: 14,
        path: "img_14_172.jpg",
      },
      {
        image_id: 173,
        boat_id: 14,
        path: "img_14_173.jpg",
      },
      {
        image_id: 174,
        boat_id: 14,
        path: "img_14_174.jpg",
      },
      {
        image_id: 175,
        boat_id: 14,
        path: "img_14_175.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 14,
        category: "Specifications",
        attributes: ["3.5' DRAFT", "13' BEAM", "35' LOA"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 16,
    codename: "MARINERIII",
    name: "MARINER III",
    portrait: "img_16_213.jpg",
    video1:
      "http://player.vimeo.com/video/32216898?title=0&byline=0&portrait=0&loop=1",
    video2: "",
    pageviews: 5910,
    images: [
      {
        image_id: 294,
        boat_id: 16,
        path: "img_16_294.jpg",
      },
      {
        image_id: 285,
        boat_id: 16,
        path: "img_16_285.jpg",
      },
      {
        image_id: 284,
        boat_id: 16,
        path: "img_16_284.jpg",
      },
      {
        image_id: 282,
        boat_id: 16,
        path: "img_16_282.jpg",
      },
      {
        image_id: 273,
        boat_id: 16,
        path: "img_16_273.jpg",
      },
      {
        image_id: 272,
        boat_id: 16,
        path: "img_16_272.jpg",
      },
      {
        image_id: 290,
        boat_id: 16,
        path: "img_16_290.jpg",
      },
      {
        image_id: 298,
        boat_id: 16,
        path: "img_16_298.jpg",
      },
      {
        image_id: 296,
        boat_id: 16,
        path: "img_16_296.jpg",
      },
      {
        image_id: 295,
        boat_id: 16,
        path: "img_16_295.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 16,
        category: "Specifications",
        attributes: [
          "Range : 3,000 Nautical Miles @ 12.5 Knots",
          "Generators : (1) 40 kw / (1) 50 kw",
          "Mains : (2) 12V-71 N Detroit Diesels",
          "98 Gross Tons",
          "USCG Certified for up to 120 guests",
          "Draft : 8.5'",
          "Beam : 20'",
          "LOA : 122'",
          "Complete Major Restoration 1988",
          "Year Built : 1926",
          "Builder : Winslow Marine Rail and Shipbuilding",
        ],
      },
      {
        boat_id: 16,
        category: "Crew Profile",
        attributes: [
          "Captain Sean Kennedy started boating at a very early age. He began taking sailing lessons in the 1970s at the Biloxi Yacht Club. After many years on the water, he tested for and passed his 500 ton USCG captains license test at age 26. \r\nHis career aboard MARINER III started not as the captain, but as part of the refit crew in May of 1979 where he signed on as a carpenters apprentice. During that refit, they rebuilt or replaced virtually every system, and structure on the yacht restoring her to her original glory.\r\nCaptain Sean returned to MARINER III in January 1986 as her permanent captain, and has enjoyed the view from the office ever since. His first official charter as captain was a 100 day charter in the spring of 1986 providing housing for Harrison Ford during the filming of the motion picture MOSQUITO COAST.\r\nWith Captain Sean at the helm, MARINER III has been performing private and corporate charters in Florida and the Caribbean in the winter, and New England in the summer ever since.\r\nAfter being in the luxury charter business for so long, Captain Sean has forged lasting working relationships with crew members in Florida and New England that return to MARINER III when they are needed for performing charter duty in any location. One of the mainstays in the crew is Chef Francis Pavlov, whose culinary prowess is well known in the yachting community. Another key member of the crew is Susan Courson. She handles charter planning aboard MARINER III.   \r\nIn Captain Seans off time he enjoys aviation / flying seaplanes, traveling, learning, biking, woodworking, and anything boat related.\r\nHe is married and enjoys spending time with his wife, Francesca, and their two children, Finn and Morgan.\r\nCaptain Seans greatest pleasure is having happy charter clients, meeting and exceeding expectations, on schedule, and giving customers lasting memories of a great event aboard MARINER III.\r\n  \r\n\r\n",
        ],
      },
      {
        boat_id: 16,
        category: "Accommodations",
        attributes: [
          "(1) King, (1) Queen, (4) Singles, (1) V-Berth, (7) Heads",
        ],
      },
    ],
    oldVideo1:
      '<iframe src="http://player.vimeo.com/video/32216898?title=0&byline=0&portrait=0&loop=1" width="400" height="225" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>',
    oldVideo2: "",
  },
  {
    boat_id: 17,
    codename: "LIBERTY",
    name: "LIBERTY",
    portrait: "img/noImage.gif",
    video1: "//www.youtube.com/embed/fsIzuqj8wcY?rel=0",
    video2: "",
    pageviews: 3374,
    images: [
      {
        image_id: 300,
        boat_id: 17,
        path: "img_17_300.jpg",
      },
      {
        image_id: 301,
        boat_id: 17,
        path: "img_17_301.jpg",
      },
      {
        image_id: 302,
        boat_id: 17,
        path: "img_17_302.jpg",
      },
      {
        image_id: 303,
        boat_id: 17,
        path: "img_17_303.jpg",
      },
      {
        image_id: 304,
        boat_id: 17,
        path: "img_17_304.jpg",
      },
      {
        image_id: 305,
        boat_id: 17,
        path: "img_17_305.jpg",
      },
      {
        image_id: 306,
        boat_id: 17,
        path: "img_17_306.jpg",
      },
      {
        image_id: 307,
        boat_id: 17,
        path: "img_17_307.jpg",
      },
      {
        image_id: 308,
        boat_id: 17,
        path: "img_17_308.jpg",
      },
      {
        image_id: 309,
        boat_id: 17,
        path: "img_17_309.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 17,
        category: "Specifications",
        attributes: [
          "USCG CERTIFIED FOR UP TO 45 GUESTS",
          "56' HATTERAS MOTOR YACHT",
        ],
      },
    ],
    oldVideo1:
      '<iframe width="560" height="315" src="//www.youtube.com/embed/fsIzuqj8wcY?rel=0" frameborder="0" allowfullscreen></iframe>',
    oldVideo2: "",
  },
  {
    boat_id: 19,
    codename: "LIBERTY46",
    name: "LIBERTY 46",
    portrait: "img_19_349.jpg",
    video1: "",
    video2: "",
    pageviews: 185,
    images: [
      {
        image_id: 359,
        boat_id: 19,
        path: "img_19_359.jpg",
      },
      {
        image_id: 358,
        boat_id: 19,
        path: "img_19_358.jpg",
      },
      {
        image_id: 356,
        boat_id: 19,
        path: "img_19_356.jpg",
      },
      {
        image_id: 355,
        boat_id: 19,
        path: "img_19_355.jpg",
      },
      {
        image_id: 354,
        boat_id: 19,
        path: "img_19_354.jpg",
      },
      {
        image_id: 352,
        boat_id: 19,
        path: "img_19_352.jpg",
      },
      {
        image_id: 351,
        boat_id: 19,
        path: "img_19_351.jpg",
      },
      {
        image_id: 311,
        boat_id: 19,
        path: "img_19_311.jpg",
      },
      {
        image_id: 350,
        boat_id: 19,
        path: "img_19_350.jpg",
      },
      {
        image_id: 313,
        boat_id: 19,
        path: "img_19_313.jpg",
      },
      {
        image_id: 316,
        boat_id: 19,
        path: "img_19_316.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 19,
        category: "Description",
        attributes: [
          "In the late 80's, the 460 SEARAY EC reigned supreme as the largest full-production Express Cruiser on the market. With her aggressive low profile hull, long foredeck and reverse radar arch, her appeal was such that she soon became a very sought after model in Sea Ray's Large Cruiser division. The hull is modified deep vee with prop pockets and solid fiberglass construction. LIBERTY boasts the preferred, one large stateroom layout with a spacious main salon. The interior layout is elaborate with wrap around ultra suede sofas, overhead track lighting, high pressure laminate counter-tops and cabinetry. Outside on deck, the bi-level cockpit is massive with seating for a large crowd. Other notable features on deck are wide walk around side decks and a transom door to the large, custom made swim platform. Detroit 6V92TA's cruise the boat in the low 20 knot range and provide a top end of just under 30 knots. Liberty is constantly maintained mechanically and aesthetically by her knowledgeable captain/owner. ",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 20,
    codename: "SCARAB30",
    name: "SCARAB 30",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 3,
    images: [
      {
        image_id: 318,
        boat_id: 20,
        path: "img_20_318.jpg",
      },
      {
        image_id: 320,
        boat_id: 20,
        path: "img_20_320.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 20,
        category: "Specifications",
        attributes: ["Testing testing testing", "Test, test, test. "],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 21,
    codename: "MONAMOUR",
    name: "MON AMOUR",
    portrait: "img_21_332.jpg",
    video1: "",
    video2: "",
    pageviews: 1118,
    images: [
      {
        image_id: 321,
        boat_id: 21,
        path: "img_21_321.jpg",
      },
      {
        image_id: 322,
        boat_id: 21,
        path: "img_21_322.jpg",
      },
      {
        image_id: 323,
        boat_id: 21,
        path: "img_21_323.jpg",
      },
      {
        image_id: 324,
        boat_id: 21,
        path: "img_21_324.jpg",
      },
      {
        image_id: 332,
        boat_id: 21,
        path: "img_21_332.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 21,
        category: "Specifications",
        attributes: [
          "Builder:  Broward Marine\r\nLOA:  70'\r\nBeam:  18'\r\nCruising speed:  10 knots",
        ],
      },
      {
        boat_id: 21,
        category: "Description",
        attributes: ["MON AMOUR is USCG Certified for up to 49 guests."],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 22,
    codename: "SERENITYIII",
    name: "SERENITY III",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 13,
    images: [
      {
        image_id: 336,
        boat_id: 22,
        path: "img_22_336.jpg",
      },
      {
        image_id: 337,
        boat_id: 22,
        path: "img_22_337.jpg",
      },
      {
        image_id: 340,
        boat_id: 22,
        path: "img_22_340.jpg",
      },
      {
        image_id: 339,
        boat_id: 22,
        path: "img_22_339.jpg",
      },
      {
        image_id: 341,
        boat_id: 22,
        path: "img_22_341.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 22,
        category: "Specifications",
        attributes: [
          "Length  72'\r\nBeam    21'\r\nUSCG Certified for 45 guests plus 3 crew",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 23,
    codename: "MADMAX",
    name: "MAD MAX",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 41,
    images: [
      {
        image_id: 389,
        boat_id: 23,
        path: "img_23_389.jpg",
      },
      {
        image_id: 384,
        boat_id: 23,
        path: "img_23_384.jpg",
      },
      {
        image_id: 383,
        boat_id: 23,
        path: "img_23_383.jpg",
      },
      {
        image_id: 382,
        boat_id: 23,
        path: "img_23_382.jpg",
      },
      {
        image_id: 385,
        boat_id: 23,
        path: "img_23_385.jpg",
      },
      {
        image_id: 381,
        boat_id: 23,
        path: "img_23_381.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 23,
        category: "Specifications",
        attributes: [
          "USCG Certified for up to 49 guests",
          "25' BEAM",
          "60' LOA",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 24,
    codename: "ThreeBaysCruise",
    name: "THREE BAYS CRUISE",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 641,
    images: [
      {
        image_id: 401,
        boat_id: 24,
        path: "img_24_401.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 24,
        category: "Description",
        attributes: [
          "Departing from Hyannis inner harbor, we cruise through Lewis Bay, passing Hyannisport, and out into Nantucket Sound. Once in the Sound, we cruise West along the Southern coast of Cape Cod to the Osterville inlet, entering West Bay. Cruising through West Bay to, and under the Osterville draw bridge, we follow the channel around Grand Island and enter North Bay. After cruising through North Bay, we enter the Cotuit River. The Cotuit River leads to Cotuit Bay, which leads to the Sepuit River. After cruising through the Sepuit River, we re-enter West Bay at the Osterville inlet. Having circumnavigated Grand Island, we then head back into Nantucket sound, cruising East along the Southern coast of Cape Cod back to Hyannisport, then back through Lewis Bay to our dock in Hyannis inner harbor. This is a great cruise for many reasons. The majority of the cruise is in very protected waters. You'll see everything from the beautiful summer homes and yachts of the rich and famous, to wild life in it's natural habitat. Contact Keith at LANE YACHT MANAGEMENT GROUP at 508-846-4575 to discuss booking your private Three Bays Cruise.",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 25,
    codename: "BREAKAWAY",
    name: "BREAKAWAY",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 79,
    images: [
      {
        image_id: 402,
        boat_id: 25,
        path: "img_25_402.jpg",
      },
      {
        image_id: 403,
        boat_id: 25,
        path: "img_25_403.jpg",
      },
      {
        image_id: 404,
        boat_id: 25,
        path: "img_25_404.jpg",
      },
      {
        image_id: 405,
        boat_id: 25,
        path: "img_25_405.jpg",
      },
      {
        image_id: 406,
        boat_id: 25,
        path: "img_25_406.jpg",
      },
      {
        image_id: 407,
        boat_id: 25,
        path: "img_25_407.jpg",
      },
      {
        image_id: 408,
        boat_id: 25,
        path: "img_25_408.jpg",
      },
      {
        image_id: 409,
        boat_id: 25,
        path: "img_25_409.jpg",
      },
      {
        image_id: 410,
        boat_id: 25,
        path: "img_25_410.jpg",
      },
      {
        image_id: 411,
        boat_id: 25,
        path: "img_25_411.jpg",
      },
      {
        image_id: 412,
        boat_id: 25,
        path: "img_25_412.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 25,
        category: "Specifications",
        attributes: [
          "GUEST CAPACITY: currently 6 (working on 12) ",
          "REFIT: 2011",
          "DATE OF LAUNCH: 1987",
          "CRUISING SPEED: 24 knots",
          "HEIGHT: 40'",
          "DRAFT: 5' 2\"",
          "BEAM: 16'",
          "LOA: 46' 6\"",
        ],
      },
      {
        boat_id: 25,
        category: "Description",
        attributes: [
          'This world class Bertram sportfish is the popular two stateroom / two head with full shower layout. Open salon arrangement with galley down. Staterooms forward of the galley. The salon features an "L" shaped couch on the port side, entertainment center featuring TV / DVD / VCR / Stereo in the forward cabinetry. Two individual chairs and wet bar are on the starboard side of the salon. The homeport for BREAKAWAY is Fairhaven, MA.',
        ],
      },
      {
        boat_id: 25,
        category: "Accommodations",
        attributes: [
          "Guest / crew stateroom on the starboard side. Guest / crew / day head on the port side midships. VIP / Master stateroom forward with ensuite head and shower.",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 26,
    codename: "CALIBOGUEII ",
    name: "CALIBOGUE II",
    portrait: "img_26_420.jpg",
    video1: "http://www.youtube.com/embed/_20HASL4cTk?rel=0",
    video2: "",
    pageviews: 149,
    images: [
      {
        image_id: 417,
        boat_id: 26,
        path: "img_26_417.jpg",
      },
      {
        image_id: 536,
        boat_id: 26,
        path: "img_26_536.jpg",
      },
      {
        image_id: 532,
        boat_id: 26,
        path: "img_26_532.jpg",
      },
      {
        image_id: 533,
        boat_id: 26,
        path: "img_26_533.jpg",
      },
      {
        image_id: 534,
        boat_id: 26,
        path: "img_26_534.jpg",
      },
      {
        image_id: 535,
        boat_id: 26,
        path: "img_26_535.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 26,
        category: "Features",
        attributes: [
          "Water Floats",
          "Beach Toys",
          "Stand-up Paddleboards",
          "Snorkeling Gear",
          "15' Caribe with 60 hp Evinrude outboard ",
        ],
      },
      {
        boat_id: 26,
        category: "Specifications",
        attributes: [
          "Last refit: 2011",
          "Date of launch: 1985 ",
          "Range @ cruise: 750 knot miles",
          "Fuel consumption @ cruise: 2.5 gph ",
          "Cruising speed: 7.5 knots",
          "Height: 75' ",
          "Draft: 7' ",
          "Beam: 16'",
          "Length: 60' LOA",
        ],
      },
      {
        boat_id: 26,
        category: "Crew Profile",
        attributes: [
          "Shannon joined Eric aboard Calibogue II as the First Mate and Chef in the spring of 2012. She was first introduced to the joy of sailing in 2008, and began exploring the waters of New England and the Virgin Islands with Eric. Shannon is a registered dietitian and has worked in the clinical setting assisting patients with issues related to diabetes and weight management. In addition, she has a wide-range of training in catering, foodservice management, and hospitality. Shannon excels at preparing unique â€œhome cookedâ€ meals that focus on using the freshest ingredients available. In addition to her passion for cooking, Shannon enjoys camping, hiking, traveling, wakeboarding, snorkeling, stand-up paddling, scuba diving and reading. \r\n",
          "........................................................................................................................................................................   ",
          "Eric moved on from university to become a design engineer in Boston, MA. Eric grew up sailing a dinghy on a lake in Maine and began sailing in Buzzards Bay during his early professional career in Boston, MA. He obtained his 'Captain's License' while working on the design of a 60 foot custom catamaran and sailing his friends' yachts. Beyond sailing, Eric enjoys swimming, snorkeling, surfing, stand-up paddle boarding, skiing, hiking, camping, reading, traveling, yacht design, and volunteering.\r\n",
          "........................................................................................................................................................................   ",
          "Eric Martin and Shannon Simones welcome you aboard Calibogue II, the 60 foot Gulfstar Sloop. On Calibogue II, your hosts will sail you amongst mountainous tropical islands to some of the best reefs in the Caribbean, take you strolling on island trails with beautiful vistas, and help you relax on remote white sand beaches.  We are passionate about entertaining you and assuring that your stay with us is everything you imagined. ",
        ],
      },
      {
        boat_id: 26,
        category: "Accommodations",
        attributes: [
          "Number of guest heads: 2",
          "Number of guest cabins: 3",
          "Term charter number of guests: 6 plus 2 ",
        ],
      },
      {
        boat_id: 26,
        category: "Description",
        attributes: [
          "CALIBOGUE II features three staterooms. The Vee berth features full size bed with private sink, TV & DVD player, AC, large closet, and shared forward wet head. Forward Guest features over / under bunks with full sized pull out bottom bed, AC, large closet, and shared forward wet head. Master cabin has extra long queen sized bed, AC, flat screen TV & DVD player, private full head, and large closet.",
        ],
      },
    ],
    oldVideo1:
      '<iframe width="420" height="315" src="http://www.youtube.com/embed/_20HASL4cTk?rel=0" frameborder="0" allowfullscreen></iframe>',
    oldVideo2: "http://www.tomschindler.net/calibogue/salon_small.mov\r\n\r\n",
  },
  {
    boat_id: 27,
    codename: "REVOLUTION",
    name: "REVOLUTION",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 14,
    images: [
      {
        image_id: 459,
        boat_id: 27,
        path: "img_27_459.jpg",
      },
      {
        image_id: 460,
        boat_id: 27,
        path: "img_27_460.jpg",
      },
      {
        image_id: 461,
        boat_id: 27,
        path: "img_27_461.jpg",
      },
      {
        image_id: 462,
        boat_id: 27,
        path: "img_27_462.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 27,
        category: "Specifications",
        attributes: [
          "Guest Heads: (2)",
          "USCG Certified for up to 100 guests",
          "Beam: 18' 0\"",
          "Length overall: 62' 0\"",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 28,
    codename: "SEAWITCH",
    name: "SEA WITCH",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 40,
    images: [
      {
        image_id: 464,
        boat_id: 28,
        path: "img_28_464.jpg",
      },
      {
        image_id: 465,
        boat_id: 28,
        path: "img_28_465.jpg",
      },
      {
        image_id: 466,
        boat_id: 28,
        path: "img_28_466.jpg",
      },
      {
        image_id: 467,
        boat_id: 28,
        path: "img_28_467.jpg",
      },
      {
        image_id: 468,
        boat_id: 28,
        path: "img_28_468.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 28,
        category: "Specifications",
        attributes: ["56' Pearson Ketch"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 29,
    codename: "53Hatt",
    name: "53Hatt",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 0,
    images: [
      {
        image_id: 469,
        boat_id: 29,
        path: "img_29_469.jpg",
      },
      {
        image_id: 472,
        boat_id: 29,
        path: "img_29_472.jpg",
      },
      {
        image_id: 471,
        boat_id: 29,
        path: "img_29_471.jpg",
      },
      {
        image_id: 473,
        boat_id: 29,
        path: "img_29_473.jpg",
      },
      {
        image_id: 474,
        boat_id: 29,
        path: "img_29_474.jpg",
      },
      {
        image_id: 475,
        boat_id: 29,
        path: "img_29_475.jpg",
      },
      {
        image_id: 476,
        boat_id: 29,
        path: "img_29_476.jpg",
      },
      {
        image_id: 477,
        boat_id: 29,
        path: "img_29_477.jpg",
      },
      {
        image_id: 478,
        boat_id: 29,
        path: "img_29_478.jpg",
      },
      {
        image_id: 479,
        boat_id: 29,
        path: "img_29_479.jpg",
      },
      {
        image_id: 480,
        boat_id: 29,
        path: "img_29_480.jpg",
      },
      {
        image_id: 481,
        boat_id: 29,
        path: "img_29_481.jpg",
      },
      {
        image_id: 482,
        boat_id: 29,
        path: "img_29_482.jpg",
      },
      {
        image_id: 488,
        boat_id: 29,
        path: "img_29_488.jpg",
      },
      {
        image_id: 490,
        boat_id: 29,
        path: "img_29_490.jpg",
      },
      {
        image_id: 494,
        boat_id: 29,
        path: "img_29_494.jpg",
      },
      {
        image_id: 496,
        boat_id: 29,
        path: "img_29_496.jpg",
      },
      {
        image_id: 500,
        boat_id: 29,
        path: "img_29_500.jpg",
      },
      {
        image_id: 501,
        boat_id: 29,
        path: "img_29_501.jpg",
      },
      {
        image_id: 506,
        boat_id: 29,
        path: "img_29_506.jpg",
      },
    ],
    attributes: [],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 30,
    codename: "Hatt",
    name: "Hatt",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 29,
    images: [
      {
        image_id: 513,
        boat_id: 30,
        path: "img_30_513.jpg",
      },
      {
        image_id: 520,
        boat_id: 30,
        path: "img_30_520.jpg",
      },
      {
        image_id: 519,
        boat_id: 30,
        path: "img_30_519.jpg",
      },
      {
        image_id: 522,
        boat_id: 30,
        path: "img_30_522.jpg",
      },
      {
        image_id: 521,
        boat_id: 30,
        path: "img_30_521.jpg",
      },
      {
        image_id: 517,
        boat_id: 30,
        path: "img_30_517.jpg",
      },
      {
        image_id: 511,
        boat_id: 30,
        path: "img_30_511.jpg",
      },
      {
        image_id: 515,
        boat_id: 30,
        path: "img_30_515.jpg",
      },
      {
        image_id: 518,
        boat_id: 30,
        path: "img_30_518.jpg",
      },
      {
        image_id: 516,
        boat_id: 30,
        path: "img_30_516.jpg",
      },
      {
        image_id: 510,
        boat_id: 30,
        path: "img_30_510.jpg",
      },
      {
        image_id: 512,
        boat_id: 30,
        path: "img_30_512.jpg",
      },
      {
        image_id: 523,
        boat_id: 30,
        path: "img_30_523.jpg",
      },
      {
        image_id: 524,
        boat_id: 30,
        path: "img_30_524.jpg",
      },
      {
        image_id: 525,
        boat_id: 30,
        path: "img_30_525.jpg",
      },
      {
        image_id: 526,
        boat_id: 30,
        path: "img_30_526.jpg",
      },
      {
        image_id: 528,
        boat_id: 30,
        path: "img_30_528.jpg",
      },
      {
        image_id: 529,
        boat_id: 30,
        path: "img_30_529.jpg",
      },
      {
        image_id: 530,
        boat_id: 30,
        path: "img_30_530.jpg",
      },
      {
        image_id: 531,
        boat_id: 30,
        path: "img_30_531.jpg",
      },
    ],
    attributes: [],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 31,
    codename: "Peter",
    name: "Peter",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 6,
    images: [
      {
        image_id: 538,
        boat_id: 31,
        path: "img_31_538.jpg",
      },
      {
        image_id: 539,
        boat_id: 31,
        path: "img_31_539.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 31,
        category: "Description",
        attributes: [
          "Hung like Great Grand Pa Luciani.",
          "Built like Peter Sr.",
          "The Cunning of Peter.",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 32,
    codename: "FENDERBENDER",
    name: "FENDER BENDER",
    portrait: "img_32_600.jpg",
    video1: "//www.youtube.com/embed/-fKKZZkc5mc?rel=0",
    video2: "",
    pageviews: 5371,
    images: [
      {
        image_id: 660,
        boat_id: 32,
        path: "img_32_660.jpg",
      },
      {
        image_id: 658,
        boat_id: 32,
        path: "img_32_658.jpg",
      },
      {
        image_id: 657,
        boat_id: 32,
        path: "img_32_657.jpg",
      },
      {
        image_id: 656,
        boat_id: 32,
        path: "img_32_656.jpg",
      },
      {
        image_id: 655,
        boat_id: 32,
        path: "img_32_655.jpg",
      },
      {
        image_id: 654,
        boat_id: 32,
        path: "img_32_654.jpg",
      },
      {
        image_id: 653,
        boat_id: 32,
        path: "img_32_653.jpg",
      },
      {
        image_id: 668,
        boat_id: 32,
        path: "img_32_668.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 32,
        category: "Description",
        attributes: [
          "Buddy Davis Yachts are world class custom built vessels sought after for their fine fit and finish, and quality construction.\r\n",
        ],
      },
      {
        boat_id: 32,
        category: "Specifications",
        attributes: [
          "FENDER BENDER is a well equipt example of a true world class yacht.",
          "25 Knot Cruise",
          "5'2\" Draft",
          "18'9\" Beam",
          "58' LOA",
        ],
      },
    ],
    oldVideo1:
      '<iframe width="560" height="315" src="//www.youtube.com/embed/-fKKZZkc5mc?rel=0" frameborder="0" allowfullscreen></iframe> \r\n\r\n\r\n\r\n\r\n',
    oldVideo2: "",
  },
  {
    boat_id: 33,
    codename: "MARINER3",
    name: "MARINER 3",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 12,
    images: [
      {
        image_id: 548,
        boat_id: 33,
        path: "img_33_548.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 33,
        category: "Description",
        attributes: [
          "For charter information, please contact Capt. Sean Kennedy at (561) 320-1926 .",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 34,
    codename: "HONEYFITZ1",
    name: "HONEY FITZ1",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 18,
    images: [
      {
        image_id: 549,
        boat_id: 34,
        path: "img_34_549.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 34,
        category: "Description",
        attributes: [
          "For charter information, please call Chef Francis Pavlov at (561) 762 - 8949 .",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 35,
    codename: "Liberty310",
    name: "LIBERTY CHARTERS and WATERSPORTS",
    portrait: "img_35_567.jpg",
    video1: "",
    video2: "",
    pageviews: 28,
    images: [
      {
        image_id: 570,
        boat_id: 35,
        path: "img_35_570.jpg",
      },
      {
        image_id: 571,
        boat_id: 35,
        path: "img_35_571.jpg",
      },
      {
        image_id: 574,
        boat_id: 35,
        path: "img_35_574.jpg",
      },
    ],
    attributes: [],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 36,
    codename: "LIBERTY31",
    name: "LIBERTY 31",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 1952,
    images: [
      {
        image_id: 719,
        boat_id: 36,
        path: "img_36_719.jpg",
      },
      {
        image_id: 720,
        boat_id: 36,
        path: "img_36_720.jpg",
      },
      {
        image_id: 721,
        boat_id: 36,
        path: "img_36_721.jpg",
      },
      {
        image_id: 722,
        boat_id: 36,
        path: "img_36_722.jpg",
      },
      {
        image_id: 723,
        boat_id: 36,
        path: "img_36_723.jpg",
      },
      {
        image_id: 729,
        boat_id: 36,
        path: "img_36_729.jpg",
      },
      {
        image_id: 730,
        boat_id: 36,
        path: "img_36_730.jpg",
      },
      {
        image_id: 734,
        boat_id: 36,
        path: "img_36_734.jpg",
      },
      {
        image_id: 737,
        boat_id: 36,
        path: "img_36_737.jpg",
      },
      {
        image_id: 738,
        boat_id: 36,
        path: "img_36_738.jpg",
      },
      {
        image_id: 742,
        boat_id: 36,
        path: "img_36_742.jpg",
      },
      {
        image_id: 746,
        boat_id: 36,
        path: "img_36_746.jpg",
      },
      {
        image_id: 747,
        boat_id: 36,
        path: "img_36_747.jpg",
      },
      {
        image_id: 748,
        boat_id: 36,
        path: "img_36_748.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 36,
        category: "Specifications",
        attributes: ["11' 2\" BEAM", "31' LOA", "SEA RAY 310 SUNDANCER"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 37,
    codename: "HONEYFITZ",
    name: "HONEY FITZ",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 15,
    images: [
      {
        image_id: 578,
        boat_id: 37,
        path: "img_37_578.jpg",
      },
    ],
    attributes: [],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 38,
    codename: "MARYALICEII",
    name: "MARY ALICE II",
    portrait: "img/noImage.gif",
    video1: "http://player.vimeo.com/video/31802337",
    video2: "",
    pageviews: 6,
    images: [
      {
        image_id: 579,
        boat_id: 38,
        path: "img_38_579.jpg",
      },
    ],
    attributes: [],
    oldVideo1:
      '<iframe src="http://player.vimeo.com/video/31802337" width="400" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>',
    oldVideo2: "",
  },
  {
    boat_id: 39,
    codename: "EXPEDITIONS",
    name: "EXPEDITIONS",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 869,
    images: [
      {
        image_id: 589,
        boat_id: 39,
        path: "img_39_589.jpg",
      },
      {
        image_id: 588,
        boat_id: 39,
        path: "img_39_588.jpg",
      },
      {
        image_id: 592,
        boat_id: 39,
        path: "img_39_592.jpg",
      },
      {
        image_id: 590,
        boat_id: 39,
        path: "img_39_590.jpg",
      },
      {
        image_id: 591,
        boat_id: 39,
        path: "img_39_591.jpg",
      },
      {
        image_id: 593,
        boat_id: 39,
        path: "img_39_593.jpg",
      },
    ],
    attributes: [],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 40,
    codename: "matt",
    name: "matt",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 1,
    images: [
      {
        image_id: 594,
        boat_id: 40,
        path: "img_40_594.jpg",
      },
    ],
    attributes: [],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 41,
    codename: "OHANAFIVE",
    name: "OHANA FIVE",
    portrait: "img/noImage.gif",
    video1: "//www.youtube.com/embed/e2l2VzscTYw?rel=0",
    video2: "",
    pageviews: 335,
    images: [
      {
        image_id: 673,
        boat_id: 41,
        path: "img_41_673.jpg",
      },
      {
        image_id: 674,
        boat_id: 41,
        path: "img_41_674.jpg",
      },
      {
        image_id: 675,
        boat_id: 41,
        path: "img_41_675.jpg",
      },
      {
        image_id: 676,
        boat_id: 41,
        path: "img_41_676.jpg",
      },
      {
        image_id: 677,
        boat_id: 41,
        path: "img_41_677.jpg",
      },
      {
        image_id: 678,
        boat_id: 41,
        path: "img_41_678.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 41,
        category: "Specifications",
        attributes: [
          "TENDER: 11' 6\" BRIG - 9.8 HP",
          "DAY HEADS: 1",
          "GUEST HEADS: 2",
          "DATE OF LAUNCH: 2008",
          "GPH @ CRUISE: 65",
          "CRUISING SPEED: 28 KNOTS",
          "DRAFT: 4'6\"",
          "BEAM: 16'",
          "LOA:  61'",
          "SEA RAY SEDAN BRIDGE MOTOR YACHT",
        ],
      },
      {
        boat_id: 41,
        category: "Crew Profile",
        attributes: [
          "CAPTAIN PAUL HEGARTY -\r\n\r\nMaster License of up to 50 Gross Tons -\r\n\r\n\r\nMore than 50 years of boating experience -\r\n\r\n\r\nCaptains a variety of yachts in New England and several East Coast Ports\r\n\r\n......................................................................................................\r\n\r\n\r\n \r\n\r\nCAPTAIN DAVID ALLENBY -\r\n\r\nMaster License 100 Tons Near Coastal with Commercial Towing Endorsement -\r\n\r\n\r\nMore than 25 years of boating experience -\r\n\r\n\r\nCaptains a variety of yachts from Boston to Florida, as well as the Bahamas -\r\n\r\n\r\nChef for Ohana Five Yacht Charters\r\n\r\n",
        ],
      },
      {
        boat_id: 41,
        category: "Description",
        attributes: [
          "USCG DOCUMENTED FOR COASTWISE TRADE",
          "NO SMOKING  -  ",
          "MOVIE LIBRARY  -  ",
          "BOSE ENTERTAINMENT SYSTEM  -  ",
        ],
      },
    ],
    oldVideo1:
      '<iframe width="560" height="315" src="//www.youtube.com/embed/e2l2VzscTYw?rel=0" frameborder="0" allowfullscreen></iframe>',
    oldVideo2: "\r\n",
  },
  {
    boat_id: 42,
    codename: "CIAO",
    name: "CIAO",
    portrait: "img/noImage.gif",
    video1: "//www.youtube.com/embed/aHbTq1KmRVs?rel=0",
    video2: "",
    pageviews: 6021,
    images: [
      {
        image_id: 699,
        boat_id: 42,
        path: "img_42_699.jpg",
      },
      {
        image_id: 706,
        boat_id: 42,
        path: "img_42_706.jpg",
      },
      {
        image_id: 708,
        boat_id: 42,
        path: "img_42_708.jpg",
      },
      {
        image_id: 709,
        boat_id: 42,
        path: "img_42_709.jpg",
      },
      {
        image_id: 710,
        boat_id: 42,
        path: "img_42_710.jpg",
      },
      {
        image_id: 711,
        boat_id: 42,
        path: "img_42_711.jpg",
      },
      {
        image_id: 712,
        boat_id: 42,
        path: "img_42_712.jpg",
      },
      {
        image_id: 713,
        boat_id: 42,
        path: "img_42_713.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 42,
        category: "Specifications",
        attributes: [
          "RIB TENDER AND TOWABLE WATER TOYS",
          "AIR CONDITIONED - ALL INTERIOR SPACES",
          "TWO HEADS",
          "TWO GUEST CABINS",
          "4 GUESTS FOR TERM CHARTERS",
          "6 GUESTS FOR DAY CHARTERS",
          "2012 / 13 INTERIOR REFIT",
          "LAUNCHED 2006",
          "28 KNOT CRUISE",
          "4' DRAFT",
          "14' 7\" BEAM",
          "52' LOA",
          "52' SESSA",
        ],
      },
    ],
    oldVideo1:
      '<iframe width="560" height="315" src="//www.youtube.com/embed/aHbTq1KmRVs?rel=0" frameborder="0" allowfullscreen></iframe>\r\n\r\n',
    oldVideo2: "",
  },
  {
    boat_id: 43,
    codename: "VENTUROUS",
    name: "VENTUROUS",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 47,
    images: [
      {
        image_id: 685,
        boat_id: 43,
        path: "img_43_685.jpg",
      },
      {
        image_id: 687,
        boat_id: 43,
        path: "img_43_687.jpg",
      },
      {
        image_id: 688,
        boat_id: 43,
        path: "img_43_688.jpg",
      },
      {
        image_id: 689,
        boat_id: 43,
        path: "img_43_689.jpg",
      },
      {
        image_id: 690,
        boat_id: 43,
        path: "img_43_690.jpg",
      },
      {
        image_id: 691,
        boat_id: 43,
        path: "img_43_691.jpg",
      },
      {
        image_id: 692,
        boat_id: 43,
        path: "img_43_692.jpg",
      },
      {
        image_id: 693,
        boat_id: 43,
        path: "img_43_693.jpg",
      },
      {
        image_id: 694,
        boat_id: 43,
        path: "img_43_694.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 43,
        category: "Specifications",
        attributes: ["40 GPH", "27 Knots Cruise", "45' LOA\r\n", "AZIMUT\r\n"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 44,
    codename: "VENTUROUSRATES",
    name: "VENTUROUS RATES",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 10,
    images: [
      {
        image_id: 686,
        boat_id: 44,
        path: "img_44_686.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 44,
        category: "Specifications",
        attributes: [
          "(24) Hours $3,900.00 Plus all expenses",
          "(8) Hours $2,950.00 Plus all expenses",
          "(6) Hours $2,350.00 Plus all expenses",
          "(4) Hours $1,750.00 Plus all expenses",
        ],
      },
      {
        boat_id: 44,
        category: "Description",
        attributes: ["RATES:"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 45,
    codename: "FENDERBENDERRates",
    name: "FENDER BENDER Rates",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 6,
    images: [
      {
        image_id: 696,
        boat_id: 45,
        path: "img_45_696.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 45,
        category: "Description",
        attributes: ["Rates:"],
      },
      {
        boat_id: 45,
        category: "Specifications",
        attributes: ["$550.00 Per hour / (4) Hour minimum plus all expenses"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 46,
    codename: "OHANAFIVERates",
    name: "OHANA FIVE Rates",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 1,
    images: [
      {
        image_id: 695,
        boat_id: 46,
        path: "img_46_695.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 46,
        category: "Description",
        attributes: ["Rates:"],
      },
      {
        boat_id: 46,
        category: "Specifications",
        attributes: ["$600.00 Per hour (4) hour minimum plus all expenses"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 47,
    codename: "CIAORates",
    name: "CIAO Rates",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 0,
    images: [],
    attributes: [
      {
        boat_id: 47,
        category: "Description",
        attributes: [
          '$17,500 plus expenses for week long term charters aboard "CIAO". \r\n\r\nFor day charters, $550.00 per hour plus expenses, with a four hour minimum.\r\n',
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 48,
    codename: "REALESCAPERATES",
    name: "REAL ESCAPE RATES",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 7,
    images: [
      {
        image_id: 697,
        boat_id: 48,
        path: "img_48_697.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 48,
        category: "Description",
        attributes: ["RATES:"],
      },
      {
        boat_id: 48,
        category: "Specifications",
        attributes: [
          "Sag Harbor NY: $700.00",
          "Montauk NY: $900.00",
          "New London CT: $600.00",
          "Goodspeed Opera House, East Haddem, CT: $600.00",
          "Mystic CT: $600.00",
          "Port Jefferson NY: $1,500.00",
          "Norwalk CT: $1,700.00",
          "Greenwich, CT: $2,000.00",
          "New York City: $3,000.00",
          "Boston MA: $4,000.00",
          "Nantucket MA: $3,600.00",
          "Oyster Bay NY: $3,000.00",
          "Hyannis MA: $3,600.00",
          "Falmouth MA: $3,200.00",
          "Martha's Vineyard: $3,200.00",
          "Newport RI: $2,000.00",
          "Popular delivery destinations:",
          "Food and beverage service not included: We provide catering, or you may bring your own. All caterers must pay a 15% galley charge. Servers, bartender, and karaoke host are extra.",
          "Gratuity: Customary gratuity is 15% to 20%.",
          "Reposition rate: $25.00 per mile, plus dockage and additional minimum charter charge.",
          "Weekly charter rate: $18,000.00 plus all expenses. Maximum (6) guests.",
          "Charter rate over night: $4,000.00 plus expenses, maximum (6) guests.",
          "If the charter has more than 24 guests, add 10% for extra crew.",
          "Minimum $3,000.00 if vessel has to be repositioned.",
          "Daily charter rate: $600.00 per hour plus 20% crew fee, minimum (2) hours departing from Old Saybrook, CT.",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 49,
    codename: "VALIANT",
    name: "VALIANT",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 80,
    images: [
      {
        image_id: 698,
        boat_id: 49,
        path: "img_49_698.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 49,
        category: "Specifications",
        attributes: ["USCG certified - 100 guests", "97' LOA"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 50,
    codename: "JosephSKennedy",
    name: "Joseph S. Kennedy",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 4,
    images: [
      {
        image_id: 704,
        boat_id: 50,
        path: "img_50_704.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 50,
        category: "Specifications",
        attributes: ["USCG Certified for up to 49 guests", "50' LOA"],
      },
      {
        boat_id: 50,
        category: "Description",
        attributes: ["Private and Corporate Charters in Boston Harbor"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 51,
    codename: "VENTUROUSCONTACT",
    name: "VENTUROUSCONTACT",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 4,
    images: [
      {
        image_id: 749,
        boat_id: 51,
        path: "img_51_749.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 51,
        category: "Specifications",
        attributes: ["508-345-5798", "BRIAN AHERN"],
      },
      {
        boat_id: 51,
        category: "Description",
        attributes: ["CHARTER CONTACT INFO:"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 52,
    codename: "parteetime",
    name: "PAR TEE TIME",
    portrait: "img/noImage.gif",
    video1: "//www.youtube.com/embed/xx-Bjd9ot9M?rel=0",
    video2: "",
    pageviews: 3041,
    images: [
      {
        image_id: 794,
        boat_id: 52,
        path: "img_52_794.jpg",
      },
      {
        image_id: 793,
        boat_id: 52,
        path: "img_52_793.jpg",
      },
      {
        image_id: 792,
        boat_id: 52,
        path: "img_52_792.jpg",
      },
      {
        image_id: 791,
        boat_id: 52,
        path: "img_52_791.jpg",
      },
      {
        image_id: 790,
        boat_id: 52,
        path: "img_52_790.jpg",
      },
      {
        image_id: 789,
        boat_id: 52,
        path: "img_52_789.jpg",
      },
      {
        image_id: 788,
        boat_id: 52,
        path: "img_52_788.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 52,
        category: "Accommodations",
        attributes: [
          'Midship guest cabin: Full and Twin berths, 12" TV, AC, ensuite head.',
          'CABIN DESCRIPTIONS : Forward master stateroom, queen size bed with ensuite head, 13" TV with BOSE surround sound, AC. \r\n',
          "NUMBER OF DAY HEADS : 1",
          "NUMBER OF GUEST HEADS : 2",
          "NUMBER OF GUEST CABINS : 2",
        ],
      },
      {
        boat_id: 52,
        category: "Specifications",
        attributes: [
          "NUMBER OF CREW : 2 - 3",
          "MAX NUMBER OR GUESTS : 12",
          "DATE OF LAST REFIT : 2014",
          "BUILD DATE : 1998",
          "MAX SPEED : 32 KNOTS",
          "FUEL CONSUMPTION AT CRUISE : 20 GPH",
          "CRUISING SPEED : 9 - 12 knots",
          "DRAFT : 4.5'",
          "BEAM : 15'",
          "LOA : 55'",
          "SEA RAY - EXPRESS YACHT",
        ],
      },
      {
        boat_id: 52,
        category: "Description",
        attributes: [
          "smoking allowed in designated areas only (bow)",
          "Wii gaming console, ",
          "movie library, ",
          "BOSE AM/FM/CD Stereo, speakers in cockpit, bridge deck, main salon, master cabin, ",
          "ENTERTAINMENT SYSTEM / EQUIPMENT:",
        ],
      },
      {
        boat_id: 52,
        category: "Features",
        attributes: [
          "Fishing allowed from the swim platform.\r\nVessel licensed. Light tackle and gear onboard",
          "TNT Hydraulic swim platform / tender launch system",
          "SCUBA gear",
          "Hookah snorkel air pump - 60' feed lines",
          "Snorkeling gear (4) sets",
          "(2) Paddleboards",
          "Yamaha Waverunner",
          "15' Phoenix w/ 20 hp Mercury O/B - 6 guests capacity",
          "TENDERS : ",
        ],
      },
    ],
    oldVideo1:
      '<iframe width="560" height="315" src="//www.youtube.com/embed/xx-Bjd9ot9M?rel=0" frameborder="0" allowfullscreen></iframe>',
    oldVideo2: "",
  },
  {
    boat_id: 53,
    codename: "JAMESMENDES",
    name: "JAMES MENDES",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 29,
    images: [
      {
        image_id: 782,
        boat_id: 53,
        path: "img_53_782.jpg",
      },
      {
        image_id: 800,
        boat_id: 53,
        path: "img_53_800.jpg",
      },
      {
        image_id: 801,
        boat_id: 53,
        path: "img_53_801.jpg",
      },
      {
        image_id: 802,
        boat_id: 53,
        path: "img_53_802.jpg",
      },
      {
        image_id: 803,
        boat_id: 53,
        path: "img_53_803.jpg",
      },
      {
        image_id: 804,
        boat_id: 53,
        path: "img_53_804.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 53,
        category: "Description",
        attributes: [
          "  ------  E-MAIL:  jrmjr12345@hotmail.com",
          "JAMES MENDES JR. :  774-353-8614",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 54,
    codename: "OHANAFIVECONTACT",
    name: "OHANA FIVE CONTACT",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 1,
    images: [
      {
        image_id: 805,
        boat_id: 54,
        path: "img_54_805.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 54,
        category: "Description",
        attributes: [
          "For charter information, please contact Maureen Starr @ 508.564.1284 ",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 55,
    codename: "PARADIGMSHIFT",
    name: "PARADIGM SHIFT",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 66,
    images: [
      {
        image_id: 807,
        boat_id: 55,
        path: "img_55_807.jpg",
      },
      {
        image_id: 813,
        boat_id: 55,
        path: "img_55_813.jpg",
      },
      {
        image_id: 814,
        boat_id: 55,
        path: "img_55_814.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 55,
        category: "Specifications",
        attributes: ["BEAM: 24'", "LOA: 50'\r\n\r\n"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 56,
    codename: "TIMELESS",
    name: "TIMELESS",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 87,
    images: [
      {
        image_id: 815,
        boat_id: 56,
        path: "img_56_815.jpg",
      },
      {
        image_id: 816,
        boat_id: 56,
        path: "img_56_816.jpg",
      },
      {
        image_id: 817,
        boat_id: 56,
        path: "img_56_817.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 56,
        category: "Vessel Description",
        attributes: [
          "USCG CERTIFIED FOR UP TO 49 GUESTS",
          "64' BURGER MOTOR YACHT - ",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 57,
    codename: "DOUBLEDIAMOND",
    name: "DOUBLE DIAMOND",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "https://www.youtube.com/embed/0qd2LIl7ND8?rel=0",
    pageviews: 1296,
    images: [
      {
        image_id: 835,
        boat_id: 57,
        path: "img_57_835.jpg",
      },
      {
        image_id: 834,
        boat_id: 57,
        path: "img_57_834.jpg",
      },
      {
        image_id: 833,
        boat_id: 57,
        path: "img_57_833.jpg",
      },
      {
        image_id: 823,
        boat_id: 57,
        path: "img_57_823.jpg",
      },
      {
        image_id: 824,
        boat_id: 57,
        path: "img_57_824.jpg",
      },
      {
        image_id: 826,
        boat_id: 57,
        path: "img_57_826.jpg",
      },
      {
        image_id: 827,
        boat_id: 57,
        path: "img_57_827.jpg",
      },
      {
        image_id: 828,
        boat_id: 57,
        path: "img_57_828.jpg",
      },
      {
        image_id: 837,
        boat_id: 57,
        path: "img_57_837.jpg",
      },
      {
        image_id: 831,
        boat_id: 57,
        path: "img_57_831.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 57,
        category: "Accommodations",
        attributes: [
          "Starboard side cabin with bunks - AC",
          "VIP berth forward - AC",
          "Master suite portside with full head - AC",
          "GUEST HEADS: 3",
          "GUEST CABINS: 3",
        ],
      },
      {
        boat_id: 57,
        category: "Specifications",
        attributes: [
          "DATE OF LAST REFIT: 2015",
          "DATE OF LAUNCH: 1999",
          "RANGE @ CRUISE: 350 Miles",
          "FUEL CONSUMPTION: 100 GPH @ Cruise",
          "CRUISING SPEED: 28 Knots",
          "HEIGHT: 32'",
          "DRAFT: 5' 1\"",
          "BEAM: 18'",
          "LOA: 58'",
          "VIKING",
        ],
      },
      {
        boat_id: 57,
        category: "Features",
        attributes: [
          "Fishing Equipment - fully stocked",
          "SCUBA Diving permitted with dive master",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/0qd2LIl7ND8?rel=0" frameborder="0" allowfullscreen></iframe>',
  },
  {
    boat_id: 58,
    codename: "BLUEWATERGRILL",
    name: "BLUEWATER GRILL",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 35,
    images: [],
    attributes: [
      {
        boat_id: 58,
        category: "Sample Menus",
        attributes: [
          "508-827-4263",
          "Hyannis, MA",
          "The Bluewater Grill 213 Ocean Street",
          "Lobster Roll with Cape Cod Chips: $26",
          "Pull Pork Sandwich with Cape Cod Chips: $12",
          "Buffalo Chicken Tender Wrap with Cape Cod Chips: $12",
          "Tuna Salad Wrap with Cape Cod Chips: $11",
          "Turkey BLT Wrap with Cape Cod Chips: $12",
          "(Choice of dressing: Balsamic, Honey mustard, Ranch)",
          "add grilled chicken: $7",
          "add tuna: $6",
          "add lobster salad: $21",
          "Caesar Salad: $10",
          "Garden Salad: $9",
          "Fruit Cup: $5",
          "Clam Chowder:  $6",
          "The Bluewater Grille\r\nSea Fare\r\n",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 59,
    codename: "WHENandIF",
    name: "WHEN and IF",
    portrait: "img/noImage.gif",
    video1: "https://www.youtube.com/embed/qcAN3bEp75k?rel=0",
    video2: "",
    pageviews: 8,
    images: [],
    attributes: [],
    oldVideo1:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/qcAN3bEp75k?rel=0" frameborder="0" allowfullscreen></iframe>',
    oldVideo2: "",
  },
  {
    boat_id: 60,
    codename: "blackdiamond",
    name: "BLACK DIAMOND",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 229,
    images: [
      {
        image_id: 917,
        boat_id: 60,
        path: "img_60_917.jpg",
      },
      {
        image_id: 918,
        boat_id: 60,
        path: "img_60_918.jpg",
      },
      {
        image_id: 920,
        boat_id: 60,
        path: "img_60_920.jpg",
      },
      {
        image_id: 921,
        boat_id: 60,
        path: "img_60_921.jpg",
      },
      {
        image_id: 922,
        boat_id: 60,
        path: "img_60_922.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 60,
        category: "Specifications",
        attributes: [
          "BLACK DIAMOND IS DOCUMENTED FOR COASTWISE TRADE, SO SHE CAN TAKE UP TO A MAXIMUM OF 12 GUESTS UNDER DEMISE CHARTER / PASSENGER VESSEL SAFETY ACT OF 1993. ",
          "FUEL CAPACITY: 564 gallons",
          "BEAM: 11 feet 6 inches",
          "LOA: 39 feet 8 Inches",
        ],
      },
      {
        boat_id: 60,
        category: "Description",
        attributes: ["YELLOW FIN 39"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 61,
    codename: "KNOTRIGHT",
    name: "KNOT RIGHT",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 52,
    images: [
      {
        image_id: 840,
        boat_id: 61,
        path: "img_61_840.jpg",
      },
      {
        image_id: 841,
        boat_id: 61,
        path: "img_61_841.jpg",
      },
      {
        image_id: 842,
        boat_id: 61,
        path: "img_61_842.jpg",
      },
      {
        image_id: 843,
        boat_id: 61,
        path: "img_61_843.jpg",
      },
      {
        image_id: 844,
        boat_id: 61,
        path: "img_61_844.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 61,
        category: "Specifications",
        attributes: ["42 CUSTOM BUILT TOURNANMENT SPORT FISH"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 62,
    codename: "STARFISH",
    name: "STARFISH",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 12,
    images: [
      {
        image_id: 845,
        boat_id: 62,
        path: "img_62_845.jpg",
      },
      {
        image_id: 846,
        boat_id: 62,
        path: "img_62_846.jpg",
      },
      {
        image_id: 847,
        boat_id: 62,
        path: "img_62_847.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 62,
        category: "Description",
        attributes: [
          "While not a yacht per se, she is a great vessel for celebrations of all types on the water. She operates in a unique, scenic, area on Cape Cod.\r\nSTARFISH is USCG certified to carry 40 passengers.   ",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 63,
    codename: "BAYBREEZE",
    name: "BAY BREEZE",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 65,
    images: [
      {
        image_id: 849,
        boat_id: 63,
        path: "img_63_849.jpg",
      },
      {
        image_id: 850,
        boat_id: 63,
        path: "img_63_850.jpg",
      },
      {
        image_id: 851,
        boat_id: 63,
        path: "img_63_851.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 63,
        category: "Description",
        attributes: [
          "BAY BREEZE is currently documented for coastwise trade, so she can do demise charters with up to 12 guests for private charters.\r\nShe is in the process of going thru the US Coast Guard certification process to become a CG certified passenger vessel. ",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 64,
    codename: "DOUBLEDIAMONDSPECIALS",
    name: "DOUBLE DIAMOND",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 17,
    images: [
      {
        image_id: 852,
        boat_id: 64,
        path: "img_64_852.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 64,
        category: "Description",
        attributes: [
          'For a limited time, the captain is offering "DOUBLE DIAMOND" for four hour sportfishing charter specials to Horse Shoe Shoals for $1,500.00, including fuel, plus any additional expenses.\r\n',
          "CAPTAINS CHARTER SPECIALS !!! .....  ",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 65,
    codename: "SYZYGY",
    name: "SYZYGY",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 46,
    images: [
      {
        image_id: 853,
        boat_id: 65,
        path: "img_65_853.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 65,
        category: "Description",
        attributes: [
          "SYZYGY is a Sparkman and Stephens designed 1986 Catalina 38. Loa: 38.2 ft, draft is 6.10 ft.Â ",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 66,
    codename: "38Hull",
    name: "38Hull",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 0,
    images: [
      {
        image_id: 854,
        boat_id: 66,
        path: "img_66_854.jpg",
      },
      {
        image_id: 855,
        boat_id: 66,
        path: "img_66_855.jpg",
      },
      {
        image_id: 856,
        boat_id: 66,
        path: "img_66_856.jpg",
      },
      {
        image_id: 857,
        boat_id: 66,
        path: "img_66_857.jpg",
      },
      {
        image_id: 858,
        boat_id: 66,
        path: "img_66_858.jpg",
      },
      {
        image_id: 859,
        boat_id: 66,
        path: "img_66_859.jpg",
      },
    ],
    attributes: [],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 67,
    codename: "Janet",
    name: "Janet",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 22,
    images: [
      {
        image_id: 860,
        boat_id: 67,
        path: "img_67_860.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 67,
        category: "Description",
        attributes: [
          '"STEAMPUNK By The SEA"\r\nby JANET A. LANE ---- \r\n\r\nJanet Lane ---- \r\n\r\nJanetLane93@HotMail.com ----\r\nCape Cod, USA',
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 68,
    codename: "EXPEDITION",
    name: "EXPEDITION",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 370,
    images: [
      {
        image_id: 868,
        boat_id: 68,
        path: "img_68_868.jpg",
      },
      {
        image_id: 864,
        boat_id: 68,
        path: "img_68_864.jpg",
      },
      {
        image_id: 869,
        boat_id: 68,
        path: "img_68_869.jpg",
      },
      {
        image_id: 878,
        boat_id: 68,
        path: "img_68_878.jpg",
      },
      {
        image_id: 871,
        boat_id: 68,
        path: "img_68_871.jpg",
      },
      {
        image_id: 877,
        boat_id: 68,
        path: "img_68_877.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 68,
        category: "Specifications",
        attributes: [
          "LOA: 30 feet\r\nBEAM: 10 feet\r\nDRAFT: 2.75 feet\r\nSINGLE: 3208 CAT Diesel",
          "Vessel is currently in the ship yard being repainted with a flag blue hull, all new upholstery, all new pipewelders aft top with Captains blue canvas, and all new electronics.\r\nPlease check back to see our progress as we get closer to Summer,",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 69,
    codename: "LEXINGTON",
    name: "LEXINGTON",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 20,
    images: [
      {
        image_id: 863,
        boat_id: 69,
        path: "img_69_863.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 69,
        category: "Specifications",
        attributes: ["LOA: 75 feet"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 70,
    codename: "MIDNIGHTSUN",
    name: "MIDNIGHT SUN",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 221,
    images: [
      {
        image_id: 886,
        boat_id: 70,
        path: "img_70_886.jpg",
      },
      {
        image_id: 887,
        boat_id: 70,
        path: "img_70_887.jpg",
      },
      {
        image_id: 888,
        boat_id: 70,
        path: "img_70_888.jpg",
      },
    ],
    attributes: [],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 71,
    codename: "BITOCRUMPET",
    name: "BIT O CRUMPET",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 86,
    images: [
      {
        image_id: 901,
        boat_id: 71,
        path: "img_71_901.jpg",
      },
      {
        image_id: 902,
        boat_id: 71,
        path: "img_71_902.jpg",
      },
      {
        image_id: 903,
        boat_id: 71,
        path: "img_71_903.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 71,
        category: "Description",
        attributes: [
          " ..... OUR BROCHURE IS CURRENTLY UNDER CONSTRUCTION. CHECK BACK SOON.",
          "56 SUNSEEKER MANHATTAN MOTOR YACHT",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 72,
    codename: "MYLIBERTY",
    name: "MYLIBERTY",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 168,
    images: [
      {
        image_id: 914,
        boat_id: 72,
        path: "img_72_914.jpg",
      },
      {
        image_id: 904,
        boat_id: 72,
        path: "img_72_904.jpg",
      },
      {
        image_id: 905,
        boat_id: 72,
        path: "img_72_905.jpg",
      },
      {
        image_id: 907,
        boat_id: 72,
        path: "img_72_907.jpg",
      },
      {
        image_id: 908,
        boat_id: 72,
        path: "img_72_908.jpg",
      },
    ],
    attributes: [],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 73,
    codename: "SOLEMATES",
    name: "SOLE MATES",
    portrait: "img_73_925.jpg",
    video1: "",
    video2: "",
    pageviews: 4,
    images: [
      {
        image_id: 923,
        boat_id: 73,
        path: "img_73_923.jpg",
      },
      {
        image_id: 924,
        boat_id: 73,
        path: "img_73_924.jpg",
      },
      {
        image_id: 925,
        boat_id: 73,
        path: "img_73_925.jpg",
      },
      {
        image_id: 928,
        boat_id: 73,
        path: "img_73_928.jpg",
      },
      {
        image_id: 929,
        boat_id: 73,
        path: "img_73_929.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 73,
        category: "Specifications",
        attributes: ["LOA : 38"],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 74,
    codename: "solmates",
    name: "SOL MATES",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 73,
    images: [
      {
        image_id: 926,
        boat_id: 74,
        path: "img_74_926.jpg",
      },
      {
        image_id: 927,
        boat_id: 74,
        path: "img_74_927.jpg",
      },
    ],
    attributes: [
      {
        boat_id: 74,
        category: "Specifications",
        attributes: [
          "Twin Mercruiser V8 Horizons",
          "12 foot Beam",
          "38 foot LOA",
          "SEA RAY",
        ],
      },
    ],
    oldVideo1: "",
    oldVideo2: "",
  },
  {
    boat_id: 75,
    codename: "LIBERTY34",
    name: "LIBERTY34",
    portrait: "img/noImage.gif",
    video1: "",
    video2: "",
    pageviews: 94,
    images: [
      {
        image_id: 931,
        boat_id: 75,
        path: "img_75_931.jpg",
      },
    ],
    attributes: [],
    oldVideo1: "",
    oldVideo2: "",
  },
];
